# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
      include:
            - main  # This triggers the pipeline on changes to the 'main' branch

            schedules:
              - cron: "*/5 * * * *"  # This triggers the pipeline to run every hour (adjust as needed)
                  displayName: "Run every hour"
                      branches:
                            include:
                                    - main  # This ensures that it runs on the 'main' branch

                                    pool:
                                      vmImage: 'ubuntu-latest'  # The VM image to use for the pipeline

                                      jobs:
                                      - job: BuildAndRun
                                        displayName: 'Build and Run bgmi binary with bot.py'

                                          steps:

                                            # Step 1: Checkout the code from the repository
                                              - task: Checkout@1
                                                  displayName: 'Checkout Repository'

                                                    # Step 2: Install Python and dependencies (if bot.py requires any)
                                                      - task: UsePythonVersion@0
                                                          inputs:
                                                                versionSpec: '3.x'
                                                                      addToPath: true

                                                                        - script: |
                                                                              python -m pip install --upgrade pip
                                                                                    pip install telebot  # Install any required dependencies (if a requirements.txt exists)
                                                                                        displayName: 'Install Python dependencies'

                                                                                          # Step 3: Copy the binary file (bgmi) to the appropriate directory (if needed)
                                                                                            - script: |
                                                                                                  mkdir -p /app/bin  # Create a directory to store the binary file (adjust the path if needed)
                                                                                                        cp $(Build.SourcesDirectory)/path/to/bgmi /app/bin/  # Ensure you specify the correct path to the bgmi binary
                                                                                                            displayName: 'Copy bgmi binary file'

                                                                                                              # Step 4: Run the Python script bot.py
                                                                                                                - script: |
                                                                                                                      python $(Build.SourcesDirectory)/path/to/bot.py  # Make sure to specify the correct path to the bot.py script
                                                                                                                          displayName: 'Run bot.py script'
                                                                                                                              











